### ISSUE TITLE
Failed to generate exe

### ISSUE THREAD

**Issue by peterpt** [z0noxz/powerstager#2]
VNDL52CWI2.c: In function ‘main’:
VNDL52CWI2.c:16:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (int _eSprfFF = 0; _eSprfFF < sizeof(_iVIzZpBrbO) / sizeof(_iVIzZpBrbO[0]); _eSprfFF++)
  ^
VNDL52CWI2.c:16:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
VNDL52CWI2.c:26:11: error: redefinition of ‘_eSprfFF’
  for (int _eSprfFF = 0; _eSprfFF < sizeof(_WLhBZbZQhea) / sizeof(_WLhBZbZQhea[0]); _eSprfFF++)
           ^
VNDL52CWI2.c:16:11: note: previous definition of ‘_eSprfFF’ was here
  for (int _eSprfFF = 0; _eSprfFF < sizeof(_iVIzZpBrbO) / sizeof(_iVIzZpBrbO[0]); _eSprfFF++)
           ^
VNDL52CWI2.c:26:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (int _eSprfFF = 0; _eSprfFF < sizeof(_WLhBZbZQhea) / sizeof(_WLhBZbZQhea[0]); _eSprfFF++)

[i] Shell listener        : 1.1.1.1:1111
  [i] Output                : power.exe
  [i] Target                : win32
  [i] Temp file             : _yAzyjcr
  [i] Encryption key        : tAyOLIJYBKRN8xnc0dJjESK12
  [i] Payload size          : 1754 bytes
  [i] Embedded size         : 8584 bytes
  [-] Failed to generate    : power.exe

**Comment by z0noxz** [comment]
It seems your compiler isn't very fond of the declaration of "_eSprfFF" (int _eSprfFF) at the beginning the for loop. I can change it to declare the "_eSprfFF" earlier instead, but I'm curious to the version of MingW you are using?

**Comment by peterpt** [comment]
Thanks , it is working like a charm .
My mingw is : 6.3.0 

i will do some tests to your remote shell , and maybe i will implement it in fatrat in future .
Case you want to contribute or help us with that project then feel free to join us at : 
https://github.com/Screetsec/TheFatRat

**Comment by z0noxz** [comment]
Nice! 
It might be that the Win32 part is more sensitive to the c source. I'll close this issue now then :)
