### ISSUE TITLE
setup.py install

### ISSUE THREAD

**Issue by bgxdoc** [z0noxz/powerstager#4]
root@pc: /Desktop/gittools/powerstager#._`
/setup.py install
Traceback (most recent call last):
  File "./setup.py", line 2, in <module
    from setuptools import setup
ImportError: No module named 'setuptools'
```_

i check the code and it seems setup.py requires a folder setuptools
but there is no setuptools in your repos.

**Comment by z0noxz** [comment]
You can install setuptools using pip:
`pip install setuptools`
or apt:
`apt-get install python-setuptools`

I'm not sure what system you are on, but this should cover the rest:
https://packaging.python.org/install_requirements_linux/

:)

**Comment by JavaRockstar** [comment]
I was having this problem yet I had setuptools installed. 

"pip install setuptools
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages"


However it was for Python 2.7 and my system was calling for Python 3 I used this command to install setuptools for Python3 and the set up file works flawlessly thanks all.

sudo apt-get install python3-setuptools

**Comment by z0noxz** [comment]
That is very true JavaRockstar. My bad, and thanks for pointing that out :)
pip3 install ... is also a valid alternative.

**Comment by z0noxz** [comment]
I've added a more complete list of prerequisites on the README.md including python3-setuptools.
