### ISSUE TITLE
cant start it

### ISSUE THREAD

**Issue by necony286** [z0noxz/powerstager#9]
error show up 
:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/tools/powerstager/powerstager/powerstager.py", line 19, in <module>
    import names
ImportError: No module named 'names'

**Comment by z0noxz** [comment]
The issue seems to be the missing module 'names'. Make sure you have all the required modules installed. See the README.md for a complete list under **Prerequisites (python3 modules):**
You can install modules using pip3 like this:
`pip3 install names`

**Comment by necony286** [comment]
yea i tryed "pip install names" and it did install it but when i did "pip3" it worked thx

**Comment by z0noxz** [comment]
I'm glad it helped

**Comment by necony286** [comment]
now im having trouble with 
powerstager --target win64 \
--url <url pointing the the uploaded payload> \
--output out.exe
A method parameter is missing, or malformed. Choose one of

**Comment by necony286** [comment]
@z0noxz

**Comment by z0noxz** [comment]
I think you posted the same second I closed the issue. 

However, when using the --url method a url must be provided.

eg. 
`powerstager --target win64 --url https://pastebin.com/deadbeef --output out.exe`

**Comment by necony286** [comment]
oh i was missing http:// ( thx )

**Comment by z0noxz** [comment]
If you have more problems with this, could you please open a new issue as it isn't related to the original issue about the missing module. :)

**Comment by necony286** [comment]
ok, np
